### ISSUE TITLE
Can't perform any requests (SSL?)

### ISSUE THREAD

**Issue by jdc-developer** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#34]
Hello.
I've been trying to run the service in my web server and also locally, and I couldn't in both of them.
I'm not proficient in docker, but I could manage to follow the steps in the tutorial.
When I finally got the service running, I can't make any requests into it. It always refuses the connection. I verified many times the environment data and everything and it's okay.
The main tutorial doesn't mention any SSL compulsoriness. The server shows running ok in the docker list, also I tried what's in https://developers.facebook.com/docs/whatsapp/guides/security but I am not sure if I did right.
Here's my compose:

```
version: '3'

volumes:
  whatsappMedia:
    driver: local

services:
  wacore:
    image: docker.whatsapp.biz/coreapp:v2.27.12
    command: ["/opt/whatsapp/bin/wait_on_postgres.sh", "/opt/whatsapp/bin/launch_within_docker.sh"]
    volumes:
     - whatsappMedia:/usr/local/wamedia
    env_file:
      - db.env
    environment:
      WA_DB_SSL_KEY: "private.key"
      WA_DB_SSL_CERT: "certificate.crt"
      WA_DB_SSL_CA: "ca_bundle.crt"
      WA_WEB_SECURITY_LEVEL: MODERN
      WA_SECRET: De8tr5ct1lljS
      # This is the version of the docker templates being used to run WhatsApp Business API
      WA_RUNNING_ENV_VERSION: v2.2.3
      ORCHESTRATION: DOCKER-COMPOSE
    network_mode: bridge
  waweb:
    image: docker.whatsapp.biz/web:v2.27.12
    command: ["/opt/whatsapp/bin/wait_on_postgres.sh", "/opt/whatsapp/bin/launch_within_docker.sh"]
    ports:
     - "1010:443"
    volumes:
     - whatsappMedia:/usr/local/wamedia
    env_file:
      - db.env
    environment:
      WA_DB_SSL_VERIFY: 0
      WA_DB_SSL_KEY: "private.key"
      WA_DB_SSL_CERT: "certificate.crt"
      WA_DB_SSL_CA: "ca_bundle.crt"
      WA_WEB_SECURITY_LEVEL: MODERN
      WA_SECRET: De8tr5ct1lljS
      WACORE_HOSTNAME: wacore
      # This is the version of the docker templates being used to run WhatsApp Business API
      WA_RUNNING_ENV_VERSION: v2.2.3
      ORCHESTRATION: DOCKER-COMPOSE
    depends_on:
      - "wacore"
    links:
      - wacore
    network_mode: bridge
```

So the cert files are on the same folder as the compose, is that right, and it makes sense? Also the lack of SSL makes the app impossible to reach?
The debug logs me these messages: 
**Database is not up yet - sleeping**
**getaddrinfo: Name or service not known**

What this means? When I change the WA_DB_HOSTNAME to localhost, it shows only **Database is not up yet - sleeping**, so what's wrong? I guess I must tell it which databse on server it should connect, but how do I do that?

I tried Wadebug with MySql locally and it has shown all right, except on the end when it tried to make requests into the server, so it failed with SSL EOF errors...

If you may, please, help me.
