### ISSUE TITLE
Kubernetes Ingress Service is missing

### ISSUE THREAD

**Issue by eumel8** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#54]
Currently SSL termination is done in webapp lighthttd with self signed certificate. Would be nice to have a non-ssl port exposed to setup ingress service like ingress-nginx.

PS: not sure if it's the right place for the issue. Seems configuration of Dockerfile isn't here

**Comment by mengyiyuan** [comment]
Hi @eumel8, I am not an expert with Kubernetes, please bear with my question here. Could you elaborate a bit more on what you want to setup ingress-nginx for? Thanks!

**Comment by eumel8** [comment]
@mengyiyuan , sure!
A normal use case would be to terminate Internet traffic on specific Ingress nodes and pass through traffic to the application layer:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whatsapp
  namespace: whatsapp
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: whatsapp.example.com
    http:
      paths:
      - backend:
          serviceName: whatsapp-web-service
          servicePort: 8080
        path: /
  tls:
  - hosts:
    - whatsapp.example.com
     secretName: whatsapp-example-com
```

Additinal features like LetsEncrypt certificates would be possible. 
The easiest way to get this done is an expose of a non-ssl http port, like 8080, from the container.
